# Generated by Django 5.0.6 on 2024-07-25 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
