# Generated by Django 5.0.6 on 2024-06-24 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_client_first_name_client_last_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='client',
            name='last_name',
        ),
    ]
