# Generated by Django 5.0.6 on 2024-06-24 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_remove_client_first_name_remove_client_last_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='password',
            field=models.CharField(max_length=100),
        ),
    ]
