# Generated by Django 5.0.6 on 2024-07-04 19:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_commande'),
    ]

    operations = [
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('libelle', models.CharField(max_length=100)),
                ('description', models.TextField(null=True)),
                ('prix', models.FloatField()),
                ('disponibilite', models.BooleanField()),
                ('image', models.ImageField(upload_to='images/')),
                ('commande', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='produits', to='orders.commande')),
            ],
        ),
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=100)),
                ('produits', models.ManyToManyField(null=True, to='orders.produit')),
            ],
        ),
    ]
