# Generated by Django 5.0.6 on 2024-07-06 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_produit_categorie'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produit',
            old_name='disponibilite',
            new_name='disponible',
        ),
    ]
