# Generated by Django 5.0.6 on 2024-07-25 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_rename_disponibilite_produit_disponible'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorie',
            name='produits',
            field=models.ManyToManyField(to='orders.produit'),
        ),
    ]
